window.PORTFOLIO_CONTENT = Object.freeze({
  brand: "pxrivizz",
  name: "Halil Çiftçi",
  role: "AI Developer",
  heroFocus: "AI",
  email: "halilciftci39@gmail.com",
  phone: "+90 544 691 18 63",
  country: "Kırklareli",
  portrait: "assets/images/halil-ciftci.jpeg",
  portraitAlt: "Halil Çiftçi — portrait",
  about: {
    headline: [
      { text: "EXPLORING AI" },
      { text: "BUILDING WITH CODE", accent: true },
      { text: "LEARNING BY DOING." },
    ],
    paragraphs: [
      "I'm Halil Çiftçi, a third-year Information Systems Engineering student at MSKU, based in Kırklareli. I enjoy solving problems, learning new things and turning engineering knowledge into practical projects with a team.",
      "During my software development internship at Sabancı University, I developed Moodle plugins and supported the transition to a new learning platform. At APECTRA, I lead software work for Teknofest Robolig and rocket competition projects, including robotics and Arduino development. My focus also includes AI architecture, model fine-tuning and application development.",
    ],
    facts: [
      { label: "Based in", value: "Kırklareli" },
      { label: "Focus", value: "AI Architecture" },
      { label: "Tech Stack", value: "C# / .NET · React · Flutter" },
      { label: "Mindset", value: "Problem-solving · Teamwork" },
      { label: "GPA", value: "3.76 / 4.0" },
      { label: "Education", value: "MSKU · ISE · 3rd year" },
    ],
  },
  expertise: {
    introduction: "Connected applications across backend, mobile and web — with AI architectures that bring models, tools and data together.",
    technologies: ["LLMs", "RAG", "AI Agents", "C# / .NET", "React", "Flutter"],
    services: [
      {
        title: "AI Architectures",
        description: "LLM integrations, retrieval-augmented generation and agent workflows that connect models with application data and tools.",
        tags: ["LLM Integration", "RAG", "Agent Workflows"],
        icon: "apps",
        preview: "apps",
        caption: "Models, context and tools",
      },
      {
        title: "C# / .NET",
        description: "Application backends with clear domain boundaries, connected data and APIs built for web and mobile clients.",
        tags: ["C#", ".NET", "APIs"],
        icon: "code",
        preview: "development",
        caption: "Structured code, connected systems",
      },
      {
        title: "React",
        description: "Component-driven web interfaces with responsive layouts, clear state flows and accessible interactions.",
        tags: ["React", "Components", "State management"],
        icon: "design",
        preview: "design",
        caption: "Components working together",
      },
      {
        title: "Flutter",
        description: "Cross-platform mobile experiences with reusable widgets, deliberate state management and connected services.",
        tags: ["Flutter", "Dart", "Cross-platform"],
        icon: "mobile",
        preview: "mobile",
        caption: "One codebase, mobile experiences",
      },
    ],
  },
  workTransition: {
    technologies: ["LLMs", "RAG", "AI AGENTS", "C#", ".NET", "REACT", "FLUTTER", "DART"],
    disciplines: ["AI ARCHITECTURES", "MOBILE APPS", "WEB APPLICATIONS", "AGENT WORKFLOWS"],
  },
  profile: {
    summary: "Information Systems Engineering student with experience in Moodle plugin development and LMS migration at Sabancı University, and software leadership at APECTRA. I enjoy solving problems, working with teams and turning engineering knowledge into practical projects.",
    cvUrl: "assets/documents/halil-ciftci-cv.pdf",
    education: {
      university: "Muğla Sıtkı Koçman University (MSKU)",
      degree: "Bachelor of Science · Information Systems Engineering (ISE)",
      location: "Muğla, Turkey",
      year: "2028",
      level: "3rd year",
      gpa: "3.76 / 4.0",
    },
    languages: [
      { name: "Turkish", level: "First language" },
      { name: "English", level: "B1 · Intermediate" },
    ],
    skillGroups: [
      { title: "Software & data", items: ["C# · MVC architecture", "Python", "C++", "Data analysis and interpretation"] },
      { title: "AI & machine learning", items: ["Model fine-tuning (LLMs and task-specific models)", "Machine learning and model development", "Artificial intelligence concepts"] },
      { title: "Robotics & hardware", items: ["Microcontroller and hardware programming", "Robotics programming", "Arduino", "Fusion 360 · Intermediate–senior level"] },
      { title: "Collaboration & tools", items: ["Team collaboration and leadership", "Problem-solving", "Active listening and communication", "Strategic planning and analysis", "MS Office Suite"] },
    ],
    cvProjects: [
      "Moodle Plugin Development & LMS Migration — Sabancı University",
      "Software Lead for Robolig Vehicle",
      "Car Rental System in C# — in development",
      "Real-time Stock Tracking Automation with Python",
      "Mobile Expense Tracker Application",
      "RoomQuest — Todo & Room Decoration App",
      "TARS — AI-Powered Robot (Prototype)",
      "QR-Based Attendance System for University (Testing Phase)",
    ],
    address: "Babaeski, Turkey · 39200",
  },
  experience: [
    {
      organization: "Sabancı University",
      role: "Software Development Intern",
      location: "Istanbul, Turkey",
      period: "Aug 2026 – Sep 2026",
      summary: "Contributed to Moodle development and the transition to a new learning platform.",
      highlights: ["Developed Moodle plugins to support platform requirements.", "Supported migration activities during the transition to the new system."],
    },
    {
      organization: "APECTRA",
      role: "Software Lead · Teknofest Robolig & Rocket Competition",
      location: "Sakarya, Turkey",
      period: "Sep 2025 – Present",
      summary: "Led software development and coordinated the team's software tasks.",
      highlights: ["Improved software performance and reliability.", "Designed robots and developed Arduino code for projects.", "Coordinated team efforts and project delivery."],
    },
  ],
  projects: [
    {
      id: "qr-yoklama",
      title: "QR Yoklama",
      description: "A university attendance system combining short-lived QR codes, campus network checks and location verification.",
      image: "assets/images/qr-yoklama-home.png",
      technologies: ["Next.js", "React", "TypeScript", "Prisma", "PostgreSQL"],
      url: "[PLACEHOLDER]",
      repository: "https://github.com/pxrivizz/qr_yoklama",
      theme: "cream",
      category: "Education · Full-stack web application",
      status: "Public source available",
      role: "Project owner",
      problem: "University attendance involves more than collecting names. The system needs to connect a student with the right course and session, check attendance conditions and give academic staff a manageable record.",
      solution: "A web-based attendance flow for MSKÜ: academic staff start a session, students scan a short-lived QR code, and the server checks the token, location and campus network before recording attendance. Separate entry flows serve students, academic staff and administrators.",
      architecture: [
        { title: "Web experience", description: "Next.js, React and TypeScript provide the role-based entry screens and student/teacher interfaces, styled with Tailwind CSS." },
        { title: "Identity & attendance checks", description: "Auth.js handles authentication. QR tokens use HS256 signatures and a 30-second lifetime; attendance modules handle location, network and device checks." },
        { title: "Records & reporting", description: "Prisma and PostgreSQL store courses, enrollments, attendance sessions and audit records. Excel parsing supports student-list imports with validation and preview." },
      ],
      highlights: [
        "Short-lived signed QR tokens with session-specific claims.",
        "Location checks and IPv4/IPv6 campus network rules.",
        "Student-list import from .xls and .xlsx files, including validation before saving.",
        "Attendance reporting, manual records and audit-log models.",
        "Unit-test files cover attendance, location, network, QR tokens and import logic.",
      ],
      outcome: "The public repository includes the application, database migrations and automated test code. This case study is based on the source and README; production usage and performance results have not been measured here. A public live-demo URL has not been provided.",
      screenshots: [
        { src: "assets/images/qr-yoklama-home.png", alt: "MSKÜ QR attendance homepage with session, scanning and attendance tracking steps", caption: "Homepage — screenshot provided in the project repository." },
        { src: "assets/images/qr-yoklama-login.png", alt: "Role-based sign-in portal with student, academic staff and administrator tabs", caption: "Role-based sign-in — screenshot provided in the project repository." },
      ],
      sources: [
        { label: "README and source snapshot", url: "https://github.com/pxrivizz/qr_yoklama/tree/a7b059376eb0289f0ce853213c7c4505ab22a6cc" },
      ],
    },
    {
      id: "pxrivizz-portfolio",
      title: "pxrivizz",
      description: "A personal portfolio connecting AI, web and mobile interests through a cinematic, accessible interface.",
      image: "assets/images/project-placeholder.svg",
      technologies: ["JavaScript", "CSS", "GSAP", "Lenis"],
      url: "[PLACEHOLDER]",
      repository: "[PLACEHOLDER]",
      theme: "ink",
      category: "Personal website",
      status: "In development",
      role: "Portfolio direction and content, with AI-assisted implementation.",
      problem: "Present a broad technical focus without making visitors sit through animations to find the essential information.",
      solution: "A cinematic homepage is paired with a direct, motion-free profile and dedicated project stories. Shared content keeps the different views consistent.",
      architecture: [
        { title: "Content", description: "content.js holds profile information, expertise, project records and contact details." },
        { title: "Presentation", description: "Semantic HTML and responsive CSS provide the homepage, project details and printable profile." },
        { title: "Interaction", description: "GSAP and Lenis coordinate the homepage motion; detail and profile pages use native scrolling." },
      ],
      highlights: [
        "Lightweight pointer interactions for the title and portrait.",
        "Reduced-motion alternatives and keyboard-accessible controls.",
        "Project navigation and a printable quick profile without the intro sequence.",
      ],
      outcome: "The frontend is implemented. The contact form validates locally but does not send messages; public deployment and cross-device visual checks are still pending.",
      screenshots: [],
    },
    ...["gold", "stone"].map((theme, index) => ({
      id: `project-${index + 3}`,
      title: "[PLACEHOLDER]",
      description: "[PLACEHOLDER]",
      image: "assets/images/project-placeholder.svg",
      technologies: ["[PLACEHOLDER]"],
      url: "[PLACEHOLDER]",
      repository: "[PLACEHOLDER]",
      theme,
      category: "[PLACEHOLDER]",
      status: "[PLACEHOLDER]",
      role: "[PLACEHOLDER]",
      problem: "[PLACEHOLDER]",
      solution: "[PLACEHOLDER]",
      architecture: [],
      highlights: [],
      outcome: "[PLACEHOLDER]",
      screenshots: [],
    })),
  ],
  contact: {
    description: "Have an idea involving AI, web or mobile? Let's talk about what we can build and learn together.",
    linkedin: "https://www.linkedin.com/in/halil-ciftci/",
    github: "https://github.com/pxrivizz",
    location: "Kırklareli",
    formNotice: "Preview form — messages are not sent yet.",
    validatedMessage: "Your details are valid. Nothing was sent: this form is not connected to a mail service yet.",
  },
  journal: {
    heading: "Journal",
    message: "No entries yet.",
  },
});
