import { chromium } from '@playwright/test'
import { mkdir, writeFile } from 'node:fs/promises'
const base = 'http://127.0.0.1:4173/experience/'
const out = new URL('../docs/checks/intro/', import.meta.url)
await mkdir(out, { recursive: true })
const browser = await chromium.launch({ channel: 'chrome', headless: true })
const checks = [], errors = []
const assert = (ok, label) => { if (!ok) throw new Error(label); checks.push(label) }
const ready = (page) => page.locator('canvas[data-scene-ready="true"]').waitFor()
const complete = (page) => page.locator('[data-intro-complete="true"]').waitFor()
try {
  const page = await browser.newPage({ viewport: { width: 1440, height: 960 } })
  page.on('pageerror', (error) => errors.push(error.message))
  await page.goto(base); await ready(page)
  await page.waitForTimeout(700)
  await page.screenshot({ path: new URL('01-arrival.png', out).pathname })
  await page.waitForTimeout(2400)
  await page.screenshot({ path: new URL('02-rising.png', out).pathname })
  await page.getByRole('button', { name: 'Hareketi durdur' }).click()
  const pausedY = await page.locator('.greeting-text').evaluate((node) => getComputedStyle(node).transform)
  await page.waitForTimeout(500)
  assert(await page.locator('.canvas-layer').getAttribute('data-render-mode') === 'static', 'Pause stops continuous rendering')
  assert(await page.locator('.greeting-text').evaluate((node) => getComputedStyle(node).transform) === pausedY, 'Pause holds greeting position')
  await page.getByRole('button', { name: 'Hareketi sürdür' }).click()
  await complete(page)
  await page.screenshot({ path: new URL('03-settled.png', out).pathname })
  assert(await page.locator('.greeting-text').evaluate((node) => Number(getComputedStyle(node).opacity)) === 0, 'Greeting leaves the scene as clouds rise')
  await page.getByRole('button', { name: 'Girişi yeniden oynat' }).click()
  assert(await page.locator('[data-intro-complete="false"]').count() === 1, 'Replay resets intro')
  await page.getByRole('button', { name: 'Portfolyoyu keşfet' }).click()
  await page.locator('[data-scene="hub"]').waitFor()
  await page.waitForFunction(() => document.querySelectorAll('[data-scene]').length === 1)
  assert(await page.locator('canvas').count() === 1, 'Skipping a replay preserves one Canvas')
  const mobile = await browser.newPage({ viewport: { width: 390, height: 844 }, isMobile: true, hasTouch: true, deviceScaleFactor: 3 })
  await mobile.goto(base); await ready(mobile); await complete(mobile)
  await mobile.screenshot({ path: new URL('04-mobile.png', out).pathname })
  assert(await mobile.evaluate(() => document.documentElement.scrollWidth <= innerWidth), 'Mobile has no horizontal overflow')
  const dpr = await mobile.locator('canvas').evaluate((node) => node.width / node.clientWidth)
  assert(dpr <= 1.25, `Mobile DPR capped: ${dpr}`)
  await mobile.getByRole('link', { name: 'Sade görünüm', exact: true }).click()
  await mobile.waitForFunction(() => document.querySelector('.canvas-layer')?.getAttribute('data-render-mode') === 'static')
  checks.push('Scrolling to HTML content stops rendering')
  const reduced = await browser.newPage({ reducedMotion: 'reduce' })
  const requests = []
  reduced.on('request', (request) => requests.push(request.url()))
  await reduced.goto(base)
  await reduced.getByRole('heading', { name: 'Biraz merak. Çokça üretim.' }).waitFor()
  await ready(reduced)
  assert(!requests.some((url) => /clouds\/(far|middle|near)\.png/.test(url)), 'Reduced motion skips intro and cloud downloads')
  await reduced.emulateMedia({ reducedMotion: 'no-preference' })
  assert(await reduced.locator('[data-scene="hub"]').count() === 1, 'Changing preference back does not force replay')
  const failed = await browser.newPage()
  await failed.route('**/clouds/*.png', (route) => route.abort())
  await failed.goto(base)
  await failed.getByText('Sade görünüm etkin. Tüm içerikler aşağıda.').waitFor()
  await failed.getByRole('button', { name: 'Portfolyoyu keşfet' }).click()
  await failed.getByRole('heading', { name: 'Biraz merak. Çokça üretim.' }).waitFor()
  checks.push('Failed cloud loads retain working navigation')
  assert(errors.length === 0, `No uncaught errors: ${JSON.stringify(errors)}`)
  await writeFile(new URL('results.json', out), JSON.stringify({ checks, limits: ['Real mobile hardware not tested', 'No mid-range laptop GPU benchmark'] }, null, 2))
  console.log(checks.join('\n'))
} finally { await browser.close() }
